### ISSUE TITLE
Sign up does not handle errors 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#12]
I am able to submit empty fields and still create a new user, where 202 is returned and a user id is returned as well. 

i.e command=1 is sent with no other params

return value {"status":200,"id":4} , this should be 404 if the required fields are not filled

**Comment by jasperdavey** [comment]
Empty fields should be handled in either the view or the controller. Would be a waste of network if you had to wait for a 404 with no explanation as to the reason why.

**Comment by jasperdavey** [comment]
I think the most optimal way is to have the view handle this as you can easily highlight empty fields to the user.
