### ISSUE TITLE
get user info not working 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#14]
returned info is empty 

sending paramter : command=9&id='sum number'

return value  { "status" : 200 , "info": [] }

this is also returning 200, if the user doesn't exist
# if you can run a bash file use this script to test calls to your commandLine.php

---
# !/bin/bash

URL="https://web.njit.edu/~aml35/login/commandLine.php"

PARAMS=$1

response=`curl --request POST $URL --data $PARAMS`

echo $response

---
-  save this as a *.sh file 
-  then run it as   ./*.sh <params>

i.e ./test.sh command=9&id=2
- this will display in terminal what you are sending me , if you are sending me back json use JSONLint , http://jsonlint.com/ , to verify the json format you are sending is correct

**Comment by aml35** [comment]
Please check getUserInfo once again and let me know if that is the output you were expecting.

if field left empty: {"404": "Error: Field was left empty"}

if id does not exist in Users table:  {"404": "Error: User id does not exist"}

else:  {"status":200, "info":{user_id_info}}
