### ISSUE TITLE
Known issues so far 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#20]
# no response

--login not working 
--create user
--get user info
--tags 
--get all events

**Comment by aml35** [comment]
Devin, I went to your webpage and I

-created a new user 
-logged in as a current user
-created an event

Also tested:
-get_User_Info  -> command 23
-tags -> command 11
-get_All_Events -> command 24
-get_All_Users -> command 16

**Comment by tramrattan** [comment]
Did anything change again? Cause none of that is working

**Comment by aml35** [comment]
no nothing changed

**Comment by tramrattan** [comment]
Do you see the user name and does the tags show up when you crested the
user? I have change my code since it was last work . Send me a list of all
commands you have working. It doesn't appear that you are uploading your
files to git so I can't read your code

**Comment by aml35** [comment]
yes, it did. For tags I saw a search bar. 

I just updated it.
