### ISSUE TITLE
JSON format for ALL EVENTS 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#21]
the json format sent back can not be evaluated proper. It parses however, unable to access data due to unique id #s, also I should never get back null as a response, if there are no attendees then it should be an empty [] 

format should be changed to this :
{
    "events": [{
        "id": "5",
        "data": {
            "name": "ACM",
            "owner": "1",
            "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
            "bio": "Event for CS students",
            "startDateTime": "2016-04-30 12:00:00",
            "endDateTime": "2016-04-30 13:00:00",
            "location": "GITC 2000",
            "attendees": []
        }
    }, {
        "id": "6",
        "data": {
            "name": "IEEE",
            "owner": "2",
            "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
            "bio": "Event for EE students",
            "startDateTime": "2016-05-02 15:00:00",
            "endDateTime": "2016-05-02 16:30:00",
            "location": "GITC 3000",
            "attendees": []
        }
    }]
}

////I I am getting back  this 
{
    "Events": {
        "5": {
            "name": "ACM",
            "owner": "1",
            "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
            "bio": "Event for CS students",
            "startDateTime": "2016-04-30 12:00:00",
            "endDateTime": "2016-04-30 13:00:00",
            "location": "GITC 2000",
            "attendees": null
        },
        "6": {
            "name": "IEEE",
            "owner": "2",
            "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
            "bio": "Event for EE students",
            "startDateTime": "2016-05-02 15:00:00",
            "endDateTime": "2016-05-02 16:30:00",
            "location": "GITC 3000",
            "attendees": null
        }
    }
}
# Please check all other responses that may be formatted in correctly

**Comment by aml35** [comment]
DONE
