### ISSUE TITLE
All users returned JSON format is incorrect 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#27]
should be an array of users - they way is currently send is not accessible, every id is unique (same issue as all other complaints about the json format being send ) 

this is what is being sent 

{
    "1": {
        "firstname": "Jasper",
        "lastname": "Davey",
        "email": "jmd57@njit.edu",
        "bio": "I like CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "ACM,IEEE,NJIT Robotics Club,AlcHE",
        "friends": "2",
        "createdEvents": "35",
        "pendingFriendRequests": ""
    },
    "2": {
        "firstname": "Bob",
        "lastname": "Saget",
        "email": "test@njit.edu",
        "bio": "I hate CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "WeHateCS,AA",
        "friends": "1",
        "createdEvents": "46",
        "pendingFriendRequests": ""
    },
    "3": {
        "firstname": "",
        "lastname": "",
        "email": "",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    },
    "4": {
        "firstname": "",
        "lastname": "",
        "email": "",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    },
    "7": {
        "firstname": "Anna",
        "lastname": "Smith",
        "email": "anna123@gmail.com",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    },
    "8": {
        "firstname": "Angelica",
        "lastname": "Llerena",
        "email": "llerena@njit.edu",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "8",
        "pendingFriendRequests": ""
    },
    "9": {
        "firstname": "Totaram",
        "lastname": "Ramrattan",
        "email": "tr88@njit.edu",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }
}

**Comment by aml35** [comment]
done
