### ISSUE TITLE
Future Events JSON format 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#29]
JSON format still not correct

this is what is being returned

{"id":"6","name":"IEEE","owner":"2","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for EE students","startDateTime":"2016-05-02 15:00:00","endDateTime":"2016-05-02 16:30:00","location":"GITC 3000","attendees":null}

// no null objects - should be an empty array

the format for this json should be

{ "events": [ array of events ] }

**Comment by aml35** [comment]
done
