### ISSUE TITLE
New Structure for Events 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#3]
Events needs to store the following data

name / string
owner / string - user id 
bio / string
startDateTime / dateTime
endDateTime/ dateTime
location / string
image_url / string 
tags

**Comment by jasperdavey** [comment]
Table Events includes requested structure as follows:

id : int
name : varchar
owner : varchar
image : varchar
bio : varchar
startDateTime : datetime
endDateTime : datetime
location : varchar
attendees : varchar

Variable names provided are what BackendAPI expects the variables to be called.
