### ISSUE TITLE
Tags are missing from returned events 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#31]
no tags shown 

//future events 
{"events":[{"id":"5","name":"ACM","owner":"1","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for CS students","startDateTime":"2016-04-30 12:00:00","endDateTime":"2016-04-30 13:00:00","location":"GITC 2000","attendees":""},{"id":"6","name":"IEEE","owner":"2","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for EE students","startDateTime":"2016-05-02 15:00:00","endDateTime":"2016-05-02 16:30:00","location":"GITC 3000","attendees":""}]}

//search results 
{"results":[{"id":"5","name":"ACM","startDateTime":"2016-04-30 12:00:00","endDateTime":"2016-04-30 13:00:00","location":"GITC 2000","bio":"Event for CS students","owner":"1"}]}

**Comment by aml35** [comment]
Jasper how can we get event_tags? There is not field in the Events table for tag and the Tags table is only for Users, I believe.

**Comment by jasperdavey** [comment]
This is now fixed, testing required.

**Comment by tramrattan** [comment]
Don't close a bug if it isn't tested
