### ISSUE TITLE
Need to be able to create new tags 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#32]
How do I make a request to create a new tag, that gets put into the tags table?

**Comment by jasperdavey** [comment]
This can be done using updateUserTags.php with takes as input $id and $tag. Will be creating updateEventTags.php next. Will keep this open to track development.

**Comment by jasperdavey** [comment]
updateEventTags.php now working and take the same input as updateUserTags.php. $id and $tag.
