### ISSUE TITLE
create user not working 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#36]
sending:
command=1&user_info={"tags":["#CS","#Software"],"bio":"full stack developer. "}&firstname=Devin&lastname=Ramrattan&username=tr88&email=tr88@njit.edu&password=pass123

repsonse:
{"status":404,"message":"Command not known"}

**Comment by aml35** [comment]
devin you said it was working by text...

is it working or no?

**Comment by tramrattan** [comment]
It's not working

**Comment by aml35** [comment]
DONE
