### ISSUE TITLE
get user info not working 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#37]
request:
command=9&id=2 

response
{"404":"Error: Field was left empty."}

**Comment by aml35** [comment]
DONE

**Comment by tramrattan** [comment]
-- not working for curl testing 
-- search works for curl testing now however, this might have the same issue as what search had 
main feature, has to be done

--please see if you can fix this issue 

response:
{"404":"Error: Field was left empty."}

**Comment by jasperdavey** [comment]
Could you please try this again? I just reset the database and could be the issue

**Comment by jasperdavey** [comment]
Verified working on my end

`{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"2","tags":[{"id":"7","owner":null,"tag":"#CS","nice":"2","type":"0"},{"id":"8","owner":null,"tag":"#Software","nice":"2","type":"0"}]}}`

**Comment by tramrattan** [comment]
it's the way angelica is handling the posts I am sending her. Had the same issue with search, but now search works when I test via curl, terminal. I get back ok results via Javascript and PHP post. However, this should work with curl, because curl is just sending a post.

**Comment by jasperdavey** [comment]
Hmm. Okay makes sense

**Comment by aml35** [comment]
Devin check now, I am getting same response as Jasper when testing
