### ISSUE TITLE
MAJOR ISSUE- Wrong response for creating user 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#39]
# MAJOR ISSUE - key feature of applicaiton

getting this back

{"command":"1","tags":["#ComputerScience","#CS","#Software","#NJIT"],"bio":"I am a full stack developer!!!!","firstname":"Devin","lastname":"Ramrattan","username":"tr88","password":"pass123","email":"tr88@njit.edu","image":null,"events":null,"friends":null,"pendingFriendRequests":null,"createdEvents":null}<br>{"status":200,"id":3}

**Comment by jasperdavey** [comment]
On my end, the user was successfully created. Your JSON object also seems right. What's the issue?

**Comment by tramrattan** [comment]
{"command":"1","tags":["#ComputerScience","#CS","#Software","#NJIT"],"bio":"I am a full stack developer!!!!","firstname":"Devin","lastname":"Ramrattan","username":"tr88","password":"pass123","email":"tr88@njit.edu","image":null,"events":null,"friends":null,"pendingFriendRequests":null,"createdEvents":null}, <b>
getting back all the above, cant parse it , there is also a <break> tag being sent back

**Comment by jasperdavey** [comment]
Oh okay I see. 😁

**Comment by aml35** [comment]
DONE
