### ISSUE TITLE
update to user info

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#4]
will need to return 
- username
- list of friends  // this can just be a list of user id
  // when a user accepts a friend request there should be a command to call to insert friends id into friends list 
- list of pending friend request // this can just be a list user id  

//should separate events into different fields when returning 

-list of pass events // this can just be a list of event ids 
-lost of future events attending /// this can just be a list of events ids

**Comment by jasperdavey** [comment]
Table Users includes requested structure as follows:

id : int
email : varchar
password: varchar
username : varchar
firstname : varchar
lastname : varchar
bio : varchar
image : varchar
events : varchar
friends : varchar
pendingFriendRequests : varchar
createdEvents : varchar

The names of the variables provided are what BackendAPI expects them to be.
