### ISSUE TITLE
MAJOR ISSUE- TAGS are not being saved 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#40]
this is the response when requesting user info: tags were not saved 
{"status":200,"info":[{"id":"3","firstname":"Devin","lastname":"Ramrattan","username":"tr88","email":"tr88@njit.edu","bio":"I am a full stack developer!!!!","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","createdEvents":"","pendingFriendRequests":"","tags":""}]}
# issue appears to when the user object was created in the backend or back end sending back info

{"command":"1","tags":["#ComputerScience","#CS","#Software","#NJIT"],"bio":"I am a full stack developer!!!!","firstname":"Devin","lastname":"Ramrattan","username":"tr88","password":"pass123","email":"tr88@njit.edu","image":null,"events":null,"friends":null,"pendingFriendRequests":null,"createdEvents":null}<br>{"status":200,"id":3}

**Comment by jasperdavey** [comment]
Testing and verified with output:

`{"status":200,"info":{"id":"3","email":"tr88@njit.edu","username":"tr88","firstname":"Devin","lastname":"Ramrattan","bio":"I am a full stack developer!!!!","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","tags":[{"id":"10","owner":"3","tag":"#ComputerScience","nice":"0","type":"0"},{"id":"11","owner":"3","tag":"#CS","nice":"0","type":"0"},{"id":"12","owner":"3","tag":"#Software","nice":"0","type":"0"},{"id":"13","owner":"3","tag":"#NJIT","nice":"0","type":"0"}]}}`

**Comment by tramrattan** [comment]
# issue lies in the middle end then

still getting this response 

{"status":200,"info":[{"id":"3","firstname":"Devin","lastname":"Ramrattan","username":"tr88","email":"tr88@njit.edu","bio":"I am a full stack developer!!!!","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","createdEvents":"","pendingFriendRequests":"","tags":""}]}
common.js:54 recommended events: {"events":[""]}

**Comment by aml35** [comment]
done
