### ISSUE TITLE
missing functionalities / commands 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#43]
##  # delete event  

these can be enhancements 
 -- accept friend request
 -- reject friend request 
-- remove friend

**Comment by aml35** [comment]
yes, I will be working on this, this afternoon. This is how commandLine.php will look like:

command . php file
1. SignUp.php
2. login.php
3. createEvent.php
4. createComment.php
5. updateUserBio.php
6. updateUserTag.php
7. createFriendRequest.php
8. recommendEvents.php
9. displayUserInfo.php
10. updateUserEvent.php
11. displayTags.php
12. search.php  (mine)
13. futureEventsWithFriends.php
14. removeUserTag.php
15. acceptFriendRequest.php
16. displayUsers.php
17. updateEventTags.php
18. removeEventTag.php
19. updateUserUsername.php
20. removeUserEvent.php
21. updateUserPassword.php
22. updateUserFirstname.php
23. updateUserLastname.php
24. updateUserEmail.php
25. updateEventStartDateTime.php
26. updateEventEndDateTime.php
27. updateEventName.php
28. updateEventLocation.php
29. updateEventBio.php 
30. displayPastEvents.php (to-do)
31. displayFutureEvents.php (to-do)
32. displayEventInfo.php (to-do)
33. displayEvents.php
34. displayUserFriend.php (to-do)
35. rejectFriendRequest.php
