### ISSUE TITLE
null in response for command 16 get all users 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#45]
-- json cant parse the non-quoted null

{"Users":[{"id":"1","firstname":"Jasper","lastname":"Davey","email":"jmd57@njit.edu","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"1","friends":"2","createdEvents":"13","pendingFriendRequests":""},{"id":"2","firstname":"Bob","lastname":"Saget","email":"test@njit.edu","bio":"I hate CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"1","friends":"1","createdEvents":"24","pendingFriendRequests":""},{"id":"3","firstname":"Devin","lastname":"Ramrattan","email":"tr88@njit.edu","bio":"test","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","createdEvents":"","pendingFriendRequests":""},{"id":"4","firstname":"Jasper","lastname":"Davey","email":"test@rutgers.edu","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":null,"friends":null,"createdEvents":null,"pendingFriendRequests":null},{"id":"5","firstname":"Joseph","lastname":"Emil","email":"jo123@test.com","bio":"New in NJ","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":null,"friends":null,"createdEvents":null,"pendingFriendRequests":null},{"id":"6","firstname":"","lastname":"","email":"shpe@test.com","bio":"We are a Club","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":null,"friends":null,"createdEvents":null,"pendingFriendRequests":null},{"id":"7","firstname":"","lastname":"","email":"nacme@test.com","bio":"We are a Club","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":null,"friends":null,"createdEvents":null,"pendingFriendRequests":null},{"id":"8","firstname":"","lastname":"","email":"acm@test.com","bio":"We love CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":null,"friends":null,"createdEvents":null,"pendingFriendRequests":null},{"id":"9","firstname":"Jasper","lastname":"Davey","email":"test@mit.edu","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","createdEvents":"","pendingFriendRequests":""}]}

**Comment by jasperdavey** [comment]
Try this one more time.

**Comment by jasperdavey** [comment]
Fix: Deleted all users created after change to default NULL. Left users that were created before this change. Default now empty quotes.
