### ISSUE TITLE
MAJOR KEY FEATURE- create organization not working - this was a past issue 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#47]
sending this 

command=1&user_info={"tags":["#ComputerScience","#CS","#Electrical","#NJIT","#Software","#Engineering"],"bio":"this is a test org"}&username=test&email=test@test.com&password=pass123

getting this:
{"status":404,"Error":"Please enter your firstname"}

 -- organization do not have a first or last name

**Comment by aml35** [comment]
still getting it ?

**Comment by tramrattan** [comment]
gettin this now

{"status":404,"id":"NULL"}

**Comment by aml35** [comment]
I created this as an organization and I am using curl to test my code

{"status":200,"info":{"id":"11","email":"test","username":"test123","firstname":"","lastname":"","bio":"testing","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","tags":[]}}

**Comment by tramrattan** [comment]
I sent you this, it has all the information, you may not be extracting the information properly from my post 

command=1&user_info={"tags":["#CS","#ComputerScience","#NJIT","#Electrical","#Engineering","#Software"],"bio":"this is a test organiztion"}&username=test&email=test@test.com&password=testtest

**Comment by tramrattan** [comment]
worked now
