### ISSUE TITLE
MAJOR ISSUE- KEY-FEATURE -- recommended events not working on my side

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#48]
# THIS IS A KEY FEATURE

I crated a new user with tags 

{"id":"10","email":"test@test.com","username":"test","firstname":"test","lastname":"test","bio":"this is a test profile","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","tags":[{"id":"14","owner":"10","tag":"#CS","nice":"0","type":"0"},{"id":"15","owner":"10","tag":"#ComputerScience","nice":"0","type":"0"},{"id":"16","owner":"10","tag":"#NJIT","nice":"0","type":"0"},{"id":"17","owner":"10","tag":"#Electrical","nice":"0","type":"0"},{"id":"18","owner":"10","tag":"#Engineering","nice":"0","type":"0"},{"id":"19","owner":"10","tag":"#Software","nice":"0","type":"0"}]}}

however, when I try to get recommended events I get this 
{"events":[""]}

atleast one tag should be matched with an event, I used all the tags

**Comment by aml35** [comment]
{"events":[1,2]}  //these are events id

this should be the output that you get if you enter command=8&id=10

let me know if it works on your end
