### ISSUE TITLE
MAJOR ISSUE - get future events now working

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#49]
# ? why would I need to send startDateTime?

{"status":404,"message":"Error: startDateTime empty."}

all future events should be from today to the future.

**Comment by aml35** [comment]
you do not need to enter any date just command

**Comment by aml35** [comment]
<?php

/*******_MIDDLE END**_***************
Project:  CS 490 - Group # 2        *
FileName: displayFutureEvents.php       *
By:       Angelica Llerena          *
Date:     March 15, 2016.           *
*************************************/

```
$data = json_encode($info);
//echo $data;
$J_url = "https://web.njit.edu/~jmd57/backend.php";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $J_url);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, 'json='.$data);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);

$DB_results = curl_exec($ch);
curl_close($ch);
echo $DB_results;
```

?>

this is the code

**Comment by aml35** [comment]
command = 31
