### ISSUE TITLE
Admin page 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#50]
# should we make an admin page

we will need to have these functionalities 
 -- delete user 
 -- delete event
 -- and anything else you think an admin would need that we don't already have

**Comment by jasperdavey** [comment]
deleteUser.php and deleteEvent.php are up. Assigning to Angelica so she can make these reflect on her end. Command 37 and 38

**Comment by aml35** [comment]
deleteUser.php and deleteEvent.php are being handle by Controller.

Command = 37 and command 38
