### ISSUE TITLE
weird data in friends field 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#51]
according to my userinf my friends are -  "friends":"491010" -- should this be an array? 

also there is no received  friends request or sent friends request

**Comment by tramrattan** [comment]
this is the json from all users 

{
    "Users": [{
        "id": "1",
        "firstname": "Jasper",
        "lastname": "Davey",
        "email": "jmd57@njit.edu",
        "bio": "I like CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "1",
        "friends": "21818",
        "createdEvents": "13",
        "pendingFriendRequests": "3"
    }, {
        "id": "2",
        "firstname": "Bob",
        "lastname": "Saget",
        "email": "test@njit.edu",
        "bio": "I hate CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "1",
        "friends": "1",
        "createdEvents": "24",
        "pendingFriendRequests": ""
    }, {
        "id": "3",
        "firstname": "Devin",
        "lastname": "Ramrattan",
        "email": "tr88@njit.edu",
        "bio": "test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "491010",
        "createdEvents": "",
        "pendingFriendRequests": "10"
    }, {
        "id": "9",
        "firstname": "Jasper",
        "lastname": "Davey",
        "email": "test@mit.edu",
        "bio": "I like CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "3",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "10",
        "firstname": "test",
        "lastname": "test",
        "email": "test@test.com",
        "bio": "this is a test profile",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "33",
        "createdEvents": "",
        "pendingFriendRequests": "133"
    }, {
        "id": "11",
        "firstname": "",
        "lastname": "",
        "email": "test",
        "bio": "testing",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "12",
        "firstname": "",
        "lastname": "",
        "email": "testorg@test.com",
        "bio": "test test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "13",
        "firstname": "",
        "lastname": "",
        "email": "testorg1@test.com",
        "bio": "test test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "14",
        "firstname": "",
        "lastname": "",
        "email": "testorg2@test.com",
        "bio": "test org 2",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "15",
        "firstname": "",
        "lastname": "",
        "email": "",
        "bio": "test org 2 ",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "16",
        "firstname": "",
        "lastname": "",
        "email": "testorg3@test.com",
        "bio": "test test test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "17",
        "firstname": "testuser2",
        "lastname": "testuser2",
        "email": "testuser2@test.com",
        "bio": "test user 2",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "18",
        "firstname": "",
        "lastname": "",
        "email": "nacme@njit.edu",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "11",
        "createdEvents": "",
        "pendingFriendRequests": "1"
    }]
}

**Comment by aml35** [comment]
what do you mean there is not received friend request or sent friend request

**Comment by aml35** [comment]
devin for testing, I created user 19 and 20 and made them friends

and then made user 19 friend with user 1 

now instead of getting "friends": "20, 1" what I get is "friends":"201"

this need to be fixed in jasper's end, I am just echoing info here.

**Comment by aml35** [comment]
{"id":"19","firstname":"Richard","lastname":"Smith","email":"ri123@njit.edu","bio":"Joined Events!","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"",**"friends":"201"**,"createdEvents":"","pendingFriendRequests":""},{"id":"20","firstname":"Jullian","lastname":"Smith","email":"ju123@njit.edu","bio":"Majoring in Engineering","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"19","createdEvents":"","pendingFriendRequests":""}]}

**Comment by tramrattan** [comment]
Assign it to him

**Comment by jasperdavey** [comment]
This is a bug with PHP's `explode()` and `implode()` methods. Investigating.

**Comment by tramrattan** [comment]
why not just store a JSON object in the db, pull it when you need to update it and just update date it and save it as a string. A JSON object is just a long string

**Comment by jasperdavey** [comment]
It's fixed just doing testing to confirm

**Comment by jasperdavey** [comment]
This one took some time. Adding and removing should all give you an appropriate string.
