### ISSUE TITLE
Critical  -NO pendingFriendRequest in userinfo returned  from command 9

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#52]
below is the response from calling command=9&id=3
## pending friendRequest is missing 

{
    "status": 200,
    "info": {
        "id": "3",
        "email": "tr88@njit.edu",
        "username": "tr88",
        "firstname": "Devin",
        "lastname": "Ramrattan",
        "bio": "test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "491010",
        "tags": [{
            "id": "10",
            "owner": "3",
            "tag": "#ComputerScience",
            "nice": "0",
            "type": "0"
        }, {
            "id": "12",
            "owner": "3",
            "tag": "#Software",
            "nice": "0",
            "type": "0"
        }, {
            "id": "13",
            "owner": "3",
            "tag": "#NJIT",
            "nice": "0",
            "type": "0"
        }]
    }
}

---

this is the response from getting all users , as you can see pendingFriendRequests request is present

{
        "id": "3",
        "firstname": "Devin",
        "lastname": "Ramrattan",
        "email": "tr88@njit.edu",
        "bio": "test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "491010",
        "createdEvents": "",
        "pendingFriendRequests": "10"
    }

**Comment by aml35** [comment]
This should be assigned to jasper I just echo what he reports Back to me .

**Comment by aml35** [comment]
I just assigned to  him

**Comment by jasperdavey** [comment]
`{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"1","friends":"2181819","pendingFriendRequests":"3","tags":[{"id":"7","owner":"1","tag":"#CS","nice":"2","type":"0"},{"id":"8","owner":"1","tag":"#Software","nice":"2","type":"0"}]}}`

pendingFriendRequests now part of returnUserInfo.php
