### ISSUE TITLE
No username in returned users 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#53]
this is what I am getting back, need username for Organizations 

{
    "id": "1",
    "firstname": "Jasper",
    "lastname": "Davey",
    "email": "jmd57@njit.edu",
    "bio": "I like CS",
    "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
    "events": "1",
    "friends": "2181819",
    "createdEvents": "13",
    "pendingFriendRequests": "3"
}

**Comment by jasperdavey** [comment]
`{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"1","friends":"2181819","tags":[{"id":"7","owner":"1","tag":"#CS","nice":"2","type":"0"},{"id":"8","owner":"1","tag":"#Software","nice":"2","type":"0"}]}}`

Every key and value of a user is returned using returnUserInfo.php
