### ISSUE TITLE
NO organizations being returned for get allusers 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#54]
{
    "Users": [{
        "id": "1",
        "firstname": "Jasper",
        "lastname": "Davey",
        "email": "jmd57@njit.edu",
        "bio": "I like CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "1",
        "friends": "2181819",
        "createdEvents": "13",
        "pendingFriendRequests": "3"
    }, {
        "id": "2",
        "firstname": "Bob",
        "lastname": "Saget",
        "email": "test@njit.edu",
        "bio": "I hate CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "1",
        "friends": "1",
        "createdEvents": "24",
        "pendingFriendRequests": ""
    }, {
        "id": "3",
        "firstname": "Devin",
        "lastname": "Ramrattan",
        "email": "tr88@njit.edu",
        "bio": "test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "491010",
        "createdEvents": "",
        "pendingFriendRequests": "10"
    }, {
        "id": "9",
        "firstname": "Jasper",
        "lastname": "Davey",
        "email": "test@mit.edu",
        "bio": "I like CS",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "3",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "10",
        "firstname": "test",
        "lastname": "test",
        "email": "test@test.com",
        "bio": "this is a test profile",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "33",
        "createdEvents": "",
        "pendingFriendRequests": "133"
    }, {
        "id": "11",
        "firstname": "",
        "lastname": "",
        "email": "test",
        "bio": "testing",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "12",
        "firstname": "",
        "lastname": "",
        "email": "testorg@test.com",
        "bio": "test test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "13",
        "firstname": "",
        "lastname": "",
        "email": "testorg1@test.com",
        "bio": "test test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "14",
        "firstname": "",
        "lastname": "",
        "email": "testorg2@test.com",
        "bio": "test org 2",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "15",
        "firstname": "",
        "lastname": "",
        "email": "",
        "bio": "test org 2 ",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "16",
        "firstname": "",
        "lastname": "",
        "email": "testorg3@test.com",
        "bio": "test test test",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "17",
        "firstname": "testuser2",
        "lastname": "testuser2",
        "email": "testuser2@test.com",
        "bio": "test user 2",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "18",
        "firstname": "",
        "lastname": "",
        "email": "nacme@njit.edu",
        "bio": "",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "11",
        "createdEvents": "",
        "pendingFriendRequests": "1"
    }, {
        "id": "19",
        "firstname": "Richard",
        "lastname": "Smith",
        "email": "ri123@njit.edu",
        "bio": "Joined Events!",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "201",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }, {
        "id": "20",
        "firstname": "Jullian",
        "lastname": "Smith",
        "email": "ju123@njit.edu",
        "bio": "Majoring in  Engineering",
        "image": "http:\/\/web.njit.edu\/~jmd57\/default.jpg",
        "events": "",
        "friends": "19",
        "createdEvents": "",
        "pendingFriendRequests": ""
    }]
}

**Comment by aml35** [comment]
I think id 18 is an organization and 16 and 15 as well

**Comment by tramrattan** [comment]
I had created organization don't see them in the users

**Comment by tramrattan** [comment]
the username is missing, so they probably are the organizations. Cause organizations do not have first and last names

**Comment by jasperdavey** [comment]
`{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"1","friends":"2181819","tags":[{"id":"7","owner":"1","tag":"#CS","nice":"2","type":"0"},{"id":"8","owner":"1","tag":"#Software","nice":"2","type":"0"}]}}`

Every key and value belonging to a user is returned using returnUserInfo.php

**Comment by aml35** [comment]
Devin refers to returnAllUsers.php not returnUserInfo.php

**Comment by aml35** [comment]
returnUserInfo.php does return the username but returnAllUsers does not

**Comment by jasperdavey** [comment]
returnAllUsers.php as part of the BackendAPI only returns a list of user ids.

**Comment by aml35** [comment]
yeah, never mind I got it
