### ISSUE TITLE
Comments // DB Clearing

### ISSUE THREAD

**Issue by jasperdavey** [jasperdavey/CS490Project#56]
New comment features are up including creating, deleting, updating, and returning. Also, DB will be refreshed now.

**Comment by jasperdavey** [comment]
ANOTHER CLEARING ABOUT TO OCCUR

**Comment by aml35** [comment]
creating, deleting, updating, and returning WERE ADDED TO CONTROLLER

**Comment by jasperdavey** [comment]
Last clearing done.

**Comment by tramrattan** [comment]
About time
