### ISSUE TITLE
CRITICAL ---- TAGS ARE NOT BEING SAVED WHEN EVENT IS CREATED 

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#57]
these are the fields that your saving....based on your code tags are not included..
$info['name']=$_POST['name'];
$info['bio']=$_POST['bio'];
$info['startDateTime']=$_POST['startDateTime'];
$info['endDateTime']=$_POST['endDateTime'];
$info['location']=$_POST['location'];
$info['image']=$_POST['image'];
$info['owner']=$_POST['owner'];

i am sending 
a post with tags in it as a json object 
you should check for 
$_POST['tags']

which will give you {"tags" :[ <array of tags>] }

**Comment by aml35** [comment]
displayEvents.php should now return you all the events id and with getEventInfo.php you will get all the info

**Comment by tramrattan** [comment]
Problem still exits, tags are not being saved when event is create

# this makes our whole concept broken

# this is a major issue

{"status":200,"info":{"id":"9","name":"Release Candidate","owner":"3","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"due 4\/22.........!!!!!!!!","startDateTime":"2016-04-22 18:00:00","endDateTime":"2016-04-22 00:00:00","location":"CKB","attendees":"","tags":[]}}

**Comment by tramrattan** [comment]
# these are the fields that your saving....based on your code tags are not included..

---

# this is from your createEventPhp code

$info['name']=$_POST['name'];
$info['bio']=$_POST['bio'];
$info['startDateTime']=$_POST['startDateTime'];
$info['endDateTime']=$_POST['endDateTime'];
$info['location']=$_POST['location'];
$info['image']=$_POST['image'];
$info['owner']=$_POST['owner'];

---

# i am sending

a post with tags in it as a json object 
you should check for 
$_POST['tags']

you are not checking for $_POST['tags]
which will give you {"tags" :[ ] }

i am sending a json object structured like below, you should handle it and forward to the back end accordingly

**Comment by jasperdavey** [comment]
A good tip for us to practice is to put the commits we make in the issue we are trying to solve. When committing just do `git commit -m "message.... issue #57"`. This will allow others to see where exactly the changes were made

**Comment by aml35** [comment]
{"status":200,"info":{"id":"15","name":"NACME Conference","owner":"8","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Honoring Recent Grads","startDateTime":"2016-05-12 10:00:00","endDateTime":"2016-05-12 00:00:00","location":"Campus Center Atrium","attendees":"","tags":[{"id":"42","owner":"15","tag":"0","nice":"0","type":"1"}]}}

Tags are now being saved when creating an event. It was tested through 

https://web.njit.edu/~tr88/events/views/dashboard.html

**Comment by wrg0** [comment]
How do I get the tag name?

**Comment by aml35** [comment]
I am testing why tag:"0", I chose #NJIT

**Comment by aml35** [comment]
Can I see what are your params?

**Comment by wrg0** [comment]
tag 0 must be the tag id

**Comment by tramrattan** [comment]
This what a correct event creating looks like
{"status":200,"info":{"id":"5","name":"ACM","owner":"1","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for CS students","startDateTime":"2016-04-30 12:00:00","endDateTime":"2016-04-30 13:00:00","location":"GITC 2000","attendees":null,"tags":[{"id":"14","owner":"5","tag":"#CS","nice":"2","type":"1"},{"id":"15","owner":"5","tag":"#ComputerScience","nice":"5","type":"1"},{"id":"16","owner":"5","tag":"#NJIT","nice":"7","type":"1"}]}}

---

this is one that is being created currently  

{"status":200,"info":{"id":"16","name":"ACM ","owner":"8","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Honoring Grads","startDateTime":"2016-05-12 10:00:00","endDateTime":"2016-05-12 00:00:00","location":"GITC 4200","attendees":"","tags":[{"id":"43","owner":"16","tag":"0","nice":"0","type":"1"}]}}

I think tag 0 was created because you didnt sent the correct tag information to the backend

**Comment by tramrattan** [comment]
I am sending you a you a json object 
you retrieve the JSON object from the post id tags  -- $_POST['tags']

the JSON object is formatted as :   { "tags": [ array of tags ] } , i.e { "tags" : [ "#CS", "#ComputerScience"]}

**Comment by tramrattan** [comment]
issue with my code, will fix it and update you, tags are not being sent, sending empty array

**Comment by aml35** [comment]
ok, let me know

**Comment by tramrattan** [comment]
ok nothing was wrong with my code, I had just forget to select tags:

 -- just created a test event 

here is the params I sent 

command=3&name=test&bio=test&startDateTime=2016-04-22 00:00:00&endDateTime=2016-04-22endTime:00&location=test&tags={"tags":["#CS","#ComputerScience","#NJIT","#Electrical","#Engineering","#Software","0","tags"]}&owner=3

---

this is what was saved 

{"id":"23","name":"test","owner":"3","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"test","startDateTime":"2016-04-22 00:00:00","endDateTime":"2016-04-22 00:00:00","location":"test","attendees":"","tags":[{"id":"47","owner":"23","tag":"tags","nice":"0","type":"1"}]}}

---

this is one that jasper created looks like 

{"id":"5","name":"ACM","owner":"1","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Event for CS students","startDateTime":"2016-04-30 12:00:00","endDateTime":"2016-04-30 13:00:00","location":"GITC 2000","attendees":null,"tags":[{"id":"14","owner":"5","tag":"#CS","nice":"2","type":"1"},{"id":"15","owner":"5","tag":"#ComputerScience","nice":"5","type":"1"},{"id":"16","owner":"5","tag":"#NJIT","nice":"7","type":"1"}]}}

**Comment by aml35** [comment]
{"status":200,"info":{"id":"25","name":"EOP Meeting","owner":"8","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"Only Junior","startDateTime":"2016-05-13 10:00:00","endDateTime":"2016-05-13 00:00:00","location":"KUPF Theater","attendees":"","tags":[{"id":"50","owner":"25","tag":"#NJIT","nice":"0","type":"1"},{"id":"51","owner":"25","tag":"#ComputerScience","nice":"0","type":"1"}]}}
