### ISSUE TITLE
CRITICAL - EVENT CREATED BY USER IS NOT BEING ADDED TO THE USER INFO

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#58]
I created event id 3
{"id":"3","name":"HackNJIT","owner":"3","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","bio":"code for 36 hours...
pizza will be served ","startDateTime":"2016-04-30 08:30:00","endDateTime":"2016-05-01 00:00:00","location":"athletic center ","attendees":null,"tags":[]}]}

not showing up in my info 
{"status":200,"info":{"id":"3","email":"tr88@njit.edu","username":"tr88","firstname":"Devin","lastname":"Ramrattan","bio":"EAT SLEEP CODE !!!","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"","pendingFriendRequests":"","tags":[{"id":"7","owner":"3","tag":"#CS","nice":"0","type":"0"},{"id":"8","owner":"3","tag":"#ComputerScience","nice":"0","type":"0"}]}}

**Comment by aml35** [comment]
wait, if created an event that should be in createdEvents not in events

**Comment by aml35** [comment]
assign this to Jasper to add "createdEvents" when returning user info

 $infoArray = array( 'id' => $row[ 'id' ], 'email' => $row[ 'email' ], 'username' => $row[ 'username' ],
                            'firstname' => $row[ 'firstname' ],
                            'lastname' => $row[ 'lastname' ], 'bio' => $row[ 'bio' ], 'image' => $row[ 'image' ],
                            'events' => $row[ 'events' ], 'friends' => $row[ 'friends' ], 'pendingFriendRequests' => $row[ 'pendingFriendRequests' ], 'tags' => $userTags );

**Comment by tramrattan** [comment]
I believe events is the created events, its just not being added into userinfo when a user creates an event. 
Unless events, are events the user are going to, you guys dont have any commands to handle that fyi

**Comment by aml35** [comment]
updateUserEvent.php  allows you to update the user "events"

**Comment by aml35** [comment]
never mind that has not been implemented but it could if you need it

**Comment by jasperdavey** [comment]
`{"status":200,"info":{"id":"1","email":"jmd57@njit.edu","username":"jaspy123","firstname":"Jasper","lastname":"Davey","bio":"I like CS","image":"http:\/\/web.njit.edu\/~jmd57\/default.jpg","events":"","friends":"3","pendingFriendRequests":"3","createdEvents":"4","tags":[{"id":"12","owner":"1","tag":"#CS","nice":"1","type":"0"},{"id":"13","owner":"1","tag":"#Software","nice":"1","type":"0"}]}}`

Fix verified and validated with test.
