### ISSUE TITLE
Signing up for events is not being handled

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#63]
I went through your code, don't see any command for signing for an event. So there is no way to show events a user is going to or an event the user has went to. I think we had said that we would recommend events friends are going to.How is the current friend recommended events working?

**Comment by tramrattan** [comment]
bad communication ....

**Comment by jasperdavey** [comment]
Users can signup for an event using `updateUserEvent.php` which adds the event to the user's `events` field and also adds the user to the event's `attendees` field. `returnAllFriendsEvents.php` returns all the events your friends are going to or have gone to.
