### ISSUE TITLE
Implement ($cmd==10){include 'updateUserEvent.php';}

### ISSUE THREAD

**Issue by tramrattan** [jasperdavey/CS490Project#65]
-- this is how Jasper is added users to events

**Comment by aml35** [comment]
yes there is a removeUserEvent.php also.

they are all implemented

**Comment by tramrattan** [comment]
Can you update git hib to reflect that

**Comment by aml35** [comment]
if you go to Controller/UPDATE/

updateUserEvent.php is there

**Comment by aml35** [comment]
Input: id, event

where id = user id

event = event id
